/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Ronda",
  primary: "#10B981",
  secondary: "#059669",
  splash: {
    glow: "rgba(5,150,105,0.6)",
    sallyGlow: "rgba(16,185,129,0.8)",
    pillBorder: "rgba(16,185,129,0.5)",
    pillBg: "rgba(5,150,105,0.15)",
    pillText: "#A7F3D0",
    suit: "🃏",
    suit2: "★",
  },
  slides: {
    slide2: { tint: ["rgba(16,185,129,0.55)","rgba(5,150,105,0.7)","rgba(6,32,21,0.95)"], variant: "spread" },
    slide3: { tint: ["rgba(20,184,166,0.45)","rgba(6,78,59,0.85)","rgba(6,32,21,0.95)"], variant: "fan" },
    slide4: { tint: ["rgba(245,158,11,0.45)","rgba(16,185,129,0.7)","rgba(6,32,21,0.95)"], variant: "scattered" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
